application:
  name: httpbin
  project: appDeployWww5lXWcmgf
  cloud_region: "aws/eu-west-3"
  publicly_accessible: true
routers:
  - name: main
    routes:
      - application_name: httpbin
        paths:
          - /*